First PR
kyeongminkang/SDK_dotnet_Git pull request #1
Opened 2019-11-28 06:41 UTC by kyeongminkang

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Class1.cs
> +﻿using System;
이 파일 삭제

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Convert.cs
> +using Newtonsoft.Json.Converters;
미사용 using 정리. ctrl + r + g

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Convert.cs
> +        public static JsonSerializerSettings Settings
1줄로 변경

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Convert.cs
> +    internal static class Convert
네이밍 `Convert -> Converter`

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/IError.cs
> +﻿namespace GluwProSDK
파일 제거

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Result.cs
> +    public sealed class Result<T, E> where E : IError
메소드 제거

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Result.cs
> +    public sealed class Result<E> where E : IError
메소드 제거

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Result.cs
> +    public sealed class ResultWithNoError<T>
Renaming `ResultWithNoError<T> -> Result<T>`

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/MakerBigInteger.cs
> +        public BigInteger ConvertToGluwacoinBigInteger(string amount)
이 메소드 Converter로 이동

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/MakerBigInteger.cs
> +﻿using Nethereum.Util;
옮긴 후 파일 삭제

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +﻿using GluwProSDK.Entity;
구조 변경

1. Client폴더 삭제. Client는 제일 바깥에 위치하도록 할 것
2. Utils 폴더를 만든 후, Converter.cs와 Result.cs를 Utils 폴더 내로 이동

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +        private readonly bool m__DEV__;
Renaming `m__DEV__ -> mIsDevEnv`

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +        public Client(string ApiKey, string SecretKey, string Address, string PrivateKey, bool __DEV__, string WebhookSecretKey)
1. 로컬 매개변수 소문자로 시작(Camel case)하도록 다 변경할 것 (예시 - `ApiKey -> apiKey`)

2. Renaming `__DEV__ -> isDevEnv`

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +            if (m__DEV__ == false)
if statement 순서 바꾸기

if (mIsDevEnv)
{
}
else
{
}

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +        private string GetContractAddress(ECurrency? currency, bool __DEV__)
1, private 메소드는 camel case로 네이밍

2. 메소드 반환값에서 null을 리턴할 수 있으므로 접미사로 OrNull 붙일 것

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +        private string GetContractAddress(ECurrency? currency, bool __DEV__)
Renaming `__DEV__ -> mIsDevEnv`

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +                if (__DEV__ == true)
true 빼기

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +                if (__DEV__ == true)
true 빼기

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +        private string GetTimestampSignature()
CamelCase

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +            var Timestamp = new DateTimeOffset(DateTime.UtcNow).ToUnixTimeSeconds().ToString();
여기 var 타입 쓰지 말것. string 타입이라는게 뒤에 따라오는 줄을 다 읽어야 알 수 있음.

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +            var signature = signer.EncodeUTF8AndSign(Timestamp, new EthECKey(mPrivateKey));
이건 뒤에줄 읽어도 알 수 없음. var 쓰지 말것.

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +            gluwaSignature_byte = System.Text.Encoding.UTF8.GetBytes(gluwaSignature);
언더바 안씁니다.

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +            using (System.Net.Http.HttpClient confClient = new System.Net.Http.HttpClient())
`HttpClient confClient = new HttpClient()`

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +            using (System.Net.Http.HttpClient confClient = new System.Net.Http.HttpClient())
conf client가 뭐죠? 이유 없으면 httpClient로 변경할것

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +            return result;
도달 하지 않는 코드는 제거할 것

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +                    BalanceResponse balanceresponse = await message.Content.ReadAsAsync<BalanceResponse>();
`balanceResponse`

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +        private async Task<ResultWithNoError<FeeResponse>> GetFeeAsync(ECurrency? currency)
1. CamelCase

2. private 메소드 위치 틀림.
```
Order of class variables and methods must be as follows:
public variables/properties
internal variables/properties
protected variables/properties
private variables
Exception: if a private variable is accessed by a property, it should appear right before the mapped property.
constructors
public methods
Internal methods
protected methods
private methods
```

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +            using (System.Net.Http.HttpClient confClient = new System.Net.Http.HttpClient())
위에서 언급한것과 동일(==상동)

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +                    FeeResponse feeresponse = await message.Content.ReadAsAsync<FeeResponse>();
`feeResponse`

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +            return result;
도달 하지 않는 코드

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +        public async Task<ResultWithNoError<List<TransactionResponse>>> GetListTransactionsAsync(ECurrency? currency, uint limit = 100, ETransactionStatusFilter? status = ETransactionStatusFilter.Con
너무 길어요. 매개변수 엔터로 정리하시길

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +        public async Task<ResultWithNoError<List<TransactionResponse>>> GetListTransactionsAsync(ECurrency? currency, uint limit = 100, ETransactionStatusFilter? status = ETransactionStatusFilter.Con
`ETransactionStatusFilter? status -> ETransactionStatusFilter status` 기본값 정해져있으니 타입이 Nullable이 아님

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +            using (System.Net.Http.HttpClient confClient = new System.Net.Http.HttpClient())
상동

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +                confClient.DefaultRequestHeaders.Add("X-REQUEST-SIGNATURE",
1줄로

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +                    var transactionresponse = await message.Content.ReadAsAsync<List<TransactionResponse>>();
`transactionResponse`

var 타입 쓰기 말것

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +            return result;
도달 하지 않는 코드

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +            }
`currency` 매개변수 유효성 확인이 없음 validation 해야함

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +            using (System.Net.Http.HttpClient confClient = new System.Net.Http.HttpClient())
상동

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +            return result;
도달 하지 않는 코드

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +        public async Task<ResultWithNoError<PostTransctionResponse>> PostTransactionAsync(ECurrency? currency, string amount, string target, string merchantOrderID = "", string note = "", int? expiry
expiry 매개변수 타입 변경 `int? -> int`

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +            var getfee = GetFeeAsync(currency).Result.Data.MinimumFee;
`getFee`

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +            var convertAmount = convertor.ConvertToGluwacoinBigInteger(amount);
타입 명시

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +            var convertFee = convertor.ConvertToGluwacoinBigInteger(getfee);
타입 명시

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +            var nonce = ((int)(DateTime.UtcNow - new DateTime(1970, 1, 1)).TotalSeconds);
타입 명시

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +            var messageHash = abiEncode.GetSha3ABIEncodedPacked(
타입 명시

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +            var addressRecovered = signer.Sign(messageHash, mPrivateKey);
타입 명시

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +            using (System.Net.Http.HttpClient confClient = new System.Net.Http.HttpClient())
상동

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +            return result;
도달하지 않는 코드

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +        public async Task<ResultWithNoError<byte[]>> GetPaymentQRCodeAsync(EPaymentCurrency? currency, string amount, string format = "image/png", string note = "", string merchantOrderID = "", int?
expiry 매개변수 타입 변경 `int? -> int`

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +
currency 매개변수 유효성 확인 없음.

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +        public async Task<ResultWithNoError<byte[]>> GetPaymentQRCodeAsync(EPaymentCurrency? currency, string amount, string format = "image/png", string note = "", string merchantOrderID = "", int?
`""` 이거는 다 string.Empty로 변경할 것. 전체 다 해당

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +            byte[] format_byte = new byte[format.Length];
camelCase

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +            var formatToBase64 = System.Convert.ToBase64String(format_byte);
타입 명시

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +            var formatToBase64 = System.Convert.ToBase64String(format_byte);
근데 이 변수 안쓰는데, 역할 확인해보고 안쓰면 제거해주세요

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +            var queryParams = new List<string>();
어차피 매개변수 하나니까 if문 하나로 줄이세요

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +        public async Task<ResultWithNoError<byte[]>> GetPaymentQRCodeAsync(EPaymentCurrency? currency, string amount, string format = "image/png", string note = "", string merchantOrderID = "", int?
여러줄로 만들기. 너무 김

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +            var authenticationBytes = Encoding.ASCII.GetBytes($"{mApiKey}:{mSecretKey}");
타입 명시

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +            System.Net.Http.HttpClient confClient = new System.Net.Http.HttpClient();
상동.

인데 using문으로 감싸줄것

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +            using (var response = await confClient.PostAsync(requestUri, content))
타입명시 response

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +            return result;
도달 하지 않는 코드

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +        public bool ValidateWebhook(PayLoad mpayload, string signature)
변수명이 왜 mpayload인가요?

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +            string payloadHashBase64Encode;
renaming `payloadHashBase64`

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +            else
else 빼고 그냥 return false;

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +        public bool ValidateWebhook(PayLoad mpayload, string signature)
매개변수명 규칙이 이런거 아니면 고치시길

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Models/BalanceResponse.cs
> +﻿using GluwProSDK.Entity;
ctrl + r + g

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Models/ECurrency.cs
> +﻿using System;
ctrl + r + g

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Models/EPaymentCurrency.cs
> +﻿using System;
ctrl + r + g

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Models/ETransactionStatus.cs
> +﻿using System;
ctrl + r + g

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Models/ETransactionStatusFilter.cs
> +﻿using System;
ctrl + r + g

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Models/FeeResponse.cs
> +﻿using GluwProSDK.Entity;
ctrl + r + g

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Models/PayLoad.cs
> +﻿using System;
ctrl + r + g

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Models/PayLoadData.cs
> +﻿using System;
ctrl + r + g

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Models/PostTransctionResponse.cs
> +    public sealed class PostTransctionResponse
이거 비어있는데 뭘 받아오는건지 확인된건가요?

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Models/QRCodeRequest.cs
> +    internal sealed class QRCodeRequest
internal로 선언한 이유가 있나요?

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Models/QRCodeRequest.cs
> +﻿using GluwProSDK.Entity;
ctrl + r + g

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Models/TransactionRequest.cs
> +﻿using GluwProSDK.Entity;
ctrl + r + g

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Models/TransactionRequest.cs
> +﻿using GluwProSDK.Entity;
... 이거 GluwaProSDK.Entity는 다 찾아서 고쳐주세요

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Models/TransactionResponse.cs
> +﻿using GluwProSDK.Entity;
ctrl + r + g

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/Models/TransactionResponse.cs
> +    public sealed class TransactionResponse
Gluwa.Entity.Transaction 참고해서 각 프로퍼티에 Attribute들 추가하세요.

2019-11-29 07:43 UTC, devtedlee commented on SDK_dotnet/SDK_dotnet.csproj
> +      <HintPath>..\..\..\..\..\..\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.2.0\ref\netcoreapp2.2\System.ComponentModel.Annotations.dll</HintPath>
이거 지우고 제대로된 DataAnnotation Nuget패키지 선언해주세요.

2019-12-02 02:17 UTC, kyeongminkang commented on SDK_dotnet/Models/PostTransctionResponse.cs
> +    public sealed class PostTransctionResponse
<img width="487" alt="response" src="https://user-images.githubusercontent.com/50939818/69925801-28aa1680-14f5-11ea-8ae1-875c322058e0.png">
넵! 보시는 바와 같이 response는 빈 값이고,  status code 번호 제대로 들어오는 것 체크 했습니다.

2019-12-02 02:20 UTC, kyeongminkang commented on SDK_dotnet/Models/QRCodeRequest.cs
> +    internal sealed class QRCodeRequest
넵! 현재 이 Request Class는 Client에 있는 Method에서만 사용하기 때문에, 외부에서(다른 어셈블리) 접근할 필요가 없다고 생각하여 Internal 선언하였습니다.

2019-12-02 04:20 UTC, devtedlee commented on SDK_dotnet/Models/PostTransctionResponse.cs
> +    public sealed class PostTransctionResponse
이럴거면 그냥 http status code 202 만 반환해주면 될거같은데, 굳이 저 빈 결과 반환하지 말고..

2019-12-02 04:25 UTC, devtedlee commented on SDK_dotnet/Models/QRCodeRequest.cs
> +    internal sealed class QRCodeRequest
그러면 SDK 내부에서만 쓸 클래스들 다 찾아서 internal 선언으로 바꿔주세요

2019-12-02 07:20 UTC, kyeongminkang commented on SDK_dotnet/Client/Client.cs
> +        public async Task<ResultWithNoError<byte[]>> GetPaymentQRCodeAsync(EPaymentCurrency? currency, string amount, string format = "image/png", string note = "", string merchantOrderID = "", int?
"" 를 string.Empty로 변경 시, 기본 매개변수 값은 컴파일 타임 상수여야 한다고 오류메시지가 뜹니다. 검색을 했더니, String.Empty는 상수가 아닌 읽기 전용 필드라고 합니다.

2019-12-02 07:20 UTC, kyeongminkang commented on SDK_dotnet/Client/Client.cs
> +        public async Task<ResultWithNoError<byte[]>> GetPaymentQRCodeAsync(EPaymentCurrency? currency, string amount, string format = "image/png", string note = "", string merchantOrderID = "", int?
그러므로 변경하지 않아도 될까요?

2019-12-02 07:20 UTC, kyeongminkang commented on SDK_dotnet/Models/TransactionResponse.cs
> +    public sealed class TransactionResponse
<img width="960" alt="transactionResponse" src="https://user-images.githubusercontent.com/50939818/69938008-83586800-151f-11ea-97aa-5a30cf644cd7.png">
다른 파일과 달리, 여기는 따로 어트리뷰트가 없어서 추가 하지 않았습니다..

2019-12-02 07:45 UTC, devtedlee commented on SDK_dotnet/Models/TransactionResponse.cs
> +    public sealed class TransactionResponse
넹 그냥 클라이언트 사용하는 사람이 참고하기 위해서 쓰라고 한거였는데, 생각해보니 그냥 안쓰는게 낫겠네요

2019-12-02 08:09 UTC, devtedlee requested changes
코드 고치고 Client 제대로 동작하는지 테스트까지 완료해주세요.

2019-12-02 08:09 UTC, devtedlee commented on SDK_dotnet/Models/BalanceResponse.cs
> +        [Range(0, ulong.MaxValue)]
이거 이상한데요? 그냥 프로퍼티의 타입을 long? -> ulong? 으로 바꾸면 되는거 아닌가요?

2019-12-02 08:09 UTC, devtedlee commented on SDK_dotnet/Client.cs
>      public sealed class Client
클래스명이랑 파일명을 Client -> GluwaClient로 바꾸는게 좋을거같습니다. SDK사용자 프로젝트에서 다른 클라이언트들이랑 이름 겹칠거같아서요.

2019-12-02 08:09 UTC, devtedlee commented on SDK_dotnet/Client.cs
> +            string merchantOrderID = "", int expiry = 1800)
매개변수 여러개인 메소드들은 다 이런식으로 고치죠. 애매하게 세줄 이렇게 나누면 더 가독성이 떨어져요.

```
public async Task<Result<byte[]>> getPaymentQRCodeAsync(
            EPaymentCurrency? currency, 
            string amount, 
            string format = "image/png", 
            string note = "", 
            string merchantOrderID = "", 
            int expiry = 1800
        )
```

2019-12-02 08:09 UTC, devtedlee commented on SDK_dotnet/Client.cs
> +        public async Task<Result<BalanceResponse>> getAddressAsync(ECurrency? currency)
public 메소드인데 카멜표기법으로 네이밍 된건 파스칼표기법으로 다 고쳐주세요.

2019-12-02 08:09 UTC, devtedlee commented on SDK_dotnet/Client.cs
> +            gluwaSignatureByte = Encoding.UTF8.GetBytes(gluwaSignature);
1줄로 줄이기
```
byte[] gluwaSignatureByte = Encoding.UTF8.GetBytes(gluwaSignature);
```

2019-12-02 08:09 UTC, devtedlee commented on SDK_dotnet/Client.cs
> +            formatByte = Encoding.UTF8.GetBytes(format);
이 변수는 어디서도 사용하지 않는데 선언과 할당이 되있네요.

2019-12-02 08:09 UTC, devtedlee commented on SDK_dotnet/Client.cs
> +            uint limit = 100, ETransactionStatusFilter status = ETransactionStatusFilter.Confirmed, uint offset = 0)
`status` 변수는 항상 값이 있는 매개변수이기때문에 하단 코드 에서 null 체크를 할 필요가 없습니다.
```
    if (status != null)
            {
                queryParams.Add($"status={status}");
            }
```

2019-12-02 08:09 UTC, devtedlee commented on SDK_dotnet/Utils/Result.cs
> +﻿namespace SDK_dotnet
네임스페이스 변경
`SDK_dotnet.Utils`

2019-12-02 08:09 UTC, devtedlee commented on SDK_dotnet/Utils/Converter.cs
> +namespace SDK_dotnet
네임스페이스 변경
`SDK_dotnet.Utils`

2019-12-02 08:09 UTC, devtedlee commented on SDK_dotnet/Client.cs
> +        public Client(string apiKey, string secretKey, string address, string privateKey, bool isDevEnv, string webhookSecretKey)
참고로 생성자 매개변수도 한줄에 너무 많으니 여러줄로 나눠주세요.

2019-12-02 08:17 UTC, devtedlee commented on SDK_dotnet/Client/Client.cs
> +        public async Task<ResultWithNoError<byte[]>> GetPaymentQRCodeAsync(EPaymentCurrency? currency, string amount, string format = "image/png", string note = "", string merchantOrderID = "", int?
넵. 그리고 매개변수중에 expiry 변수를 안사용하던데 이거 쓸모없으면 지워요.

2019-12-02 08:19 UTC, devtedlee commented on SDK_dotnet/Client.cs
>      public sealed class Client
그리고 namespace가 여전히 `SDK_dotnet.Client`네요. `SDK_dotnet` 으로 변경해주세요.

2019-12-02 08:28 UTC, kyeongminkang commented on SDK_dotnet/Models/BalanceResponse.cs
> +        [Range(0, ulong.MaxValue)]
아... Gluwa에 있는 것을 그대로 가져왔어요. 수정할까요?
<img width="487" alt="long" src="https://user-images.githubusercontent.com/50939818/69943810-1ba71a80-1529-11ea-9bfb-8537fc5fd02a.png">

2019-12-02 08:38 UTC, devtedlee commented on SDK_dotnet/Models/BalanceResponse.cs
> +        [Range(0, ulong.MaxValue)]
네 고쳐요

2019-12-03 02:10 UTC, devtedlee approved these changes

2019-12-03 02:10 UTC, devtedlee commented on SDK_dotnet/GluwaClient.cs
> +                    result.Data = response.StatusCode;
StatusCode를 Data에 넣어주는게 원래 PHP SDK의 구조인거죠?

2019-12-03 02:10 UTC, devtedlee commented on SDK_dotnet/GluwaClient.cs
> +                    result.Data = response.StatusCode;
아니네

2019-12-03 02:10 UTC, devtedlee commented on SDK_dotnet/GluwaClient.cs
> +                    result.Data = response.StatusCode;
PostTransactionAsync 메소드 반환타입 자체를 Task<bool>로 해도 될듯

2019-12-03 05:36 UTC, merged